services:

  postgres:
    image: postgres:16

    container_name: clinicos-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinicos

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  backend:

    container_name: clinicos-backend

    build:
      context: ./backend

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    restart: unless-stopped

volumes:
  postgres_data: