from __future__ import annotations

from typing import Any, Protocol


class DeliveryPlatformAdapter(Protocol):
    platform_name: str

    def validate_execution_plan(self, plan: Any) -> dict[str, Any]: ...
    def create_runtime_session(self, plan: Any) -> dict[str, Any]: ...
    def health_check_session(self, session: dict[str, Any]) -> dict[str, Any]: ...
    def prepare_session_for_job(self, session: dict[str, Any], plan: Any) -> dict[str, Any]: ...
    def prepare_recipient(self, session: dict[str, Any], plan: Any) -> dict[str, Any]: ...
    def deliver(self, session: dict[str, Any], plan: Any) -> dict[str, Any]: ...
    def execute_plan(self, plan: Any, runtime_session: Any | None = None) -> dict[str, Any]: ...
    def reset_session_after_job(self, session: Any, plan: Any, result: dict[str, Any]) -> dict[str, Any]: ...
    def verify_delivery(self, session: dict[str, Any], plan: Any, result: dict[str, Any]) -> dict[str, Any]: ...
    def reset_session(self, session: dict[str, Any]) -> dict[str, Any]: ...
    def close_runtime_session(self, session: dict[str, Any]) -> dict[str, Any]: ...
    def classify_error(self, result: dict[str, Any]) -> dict[str, Any]: ...
